version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
    environment:
      - FLASK_APP=main.py
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DB=CrudApp

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
